<a href="https://colab.research.google.com/github/AndreesArgueta/etl-data-pipeline/blob/main/etl_aseguradoras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/AndreesArgueta/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"

df = pd.read_csv(url)

df.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

LIMPIEZA DE DATOS

In [5]:
aseguradoras = df.copy()

aseguradoras.columns = aseguradoras.columns.str.strip().str.lower()

for col in aseguradoras.select_dtypes(include="object").columns:
    aseguradoras[col] = aseguradoras[col].astype(str).str.strip()

aseguradoras = aseguradoras.replace(r'^\s*$', pd.NA, regex=True)

aseguradoras['pais'] = aseguradoras['pais'].str.title()

aseguradoras['rating_riesgo'] = aseguradoras['rating_riesgo'].str.title()

aseguradoras = aseguradoras.drop_duplicates()

SEPARAR DATOS VALIDOS Y RECHAZADOS

In [6]:
validos = aseguradoras[
    aseguradoras['nombre'].notna() &
    aseguradoras['pais'].notna()
].copy()

rechazados = aseguradoras[
    aseguradoras['nombre'].isna() |
    aseguradoras['pais'].isna()
].copy()

MOTIVO DE RECHAZO

In [8]:
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['pais']):
        motivos.append("pais_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

EXPORTAR ARCHIVOS

In [11]:
validos.to_csv("aseguradoras_curated.csv", index=False)
rechazados.to_csv("aseguradoras_rejects.csv", index=False)

CONECTAR CON POSTRESQL

In [12]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_argueta:RuSM0PkNryjJpjcJs9z3LwZNjP3Iuoph@dpg-d6qu6ivgi27c73aaaar0-a.oregon-postgres.render.com/etl_seguros_c75s"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 68.2 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

CARGAR DATOS EN POSTGRESQL

In [14]:
validos.to_sql(
    'aseguradoras_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'aseguradoras_rejects',
    engine,
    if_exists='append',
    index=False
)

0

VALIDAR LA CARGA

In [16]:
pd.read_sql(
"SELECT * FROM aseguradoras_curated LIMIT 10",
engine)

   id_aseguradora          nombre         pais rating_riesgo
0               1   Aseguradora 1   Costa Rica          Alto
1               2   Aseguradora 2  El Salvador          Bajo
2               3   Aseguradora 3  El Salvador           Nan
3               4   Aseguradora 4   Costa Rica         Medio
4               5   Aseguradora 5   Elsalvador             B
5               6   Aseguradora 6          Nan         Medio
6               7   Aseguradora 7    Guatemala          Alto
7               8   Aseguradora 8       Panamá          Bajo
8               9   Aseguradora 9          Nan          Bajo
9              10  Aseguradora 10       Panamá           Nan