<a href="https://colab.research.google.com/github/AndreesArgueta/etl-data-pipeline/blob/main/etl_tipos_seguro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/AndreesArgueta/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv"

df = pd.read_csv(url)

df.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

LIMPIEZA DE DATOS

In [2]:
tipos_seguro = df.copy()

tipos_seguro.columns = tipos_seguro.columns.str.strip().str.lower()

for col in tipos_seguro.select_dtypes(include="object").columns:
    tipos_seguro[col] = tipos_seguro[col].astype(str).str.strip()

tipos_seguro = tipos_seguro.replace(r'^\s*$', pd.NA, regex=True)

tipos_seguro['riesgo_base'] = (
    tipos_seguro['riesgo_base']
    .astype(str)
    .str.strip()
    .replace('-', pd.NA)
)

tipos_seguro['riesgo_base'] = pd.to_numeric(
    tipos_seguro['riesgo_base'],
    errors='coerce'
)

tipos_seguro['tipo'] = tipos_seguro['tipo'].str.title()
tipos_seguro['categoria'] = tipos_seguro['categoria'].str.title()

tipos_seguro = tipos_seguro.drop_duplicates()

SEPARAR DATOS VALIDOS Y RECHAZADOS

In [3]:
validos = tipos_seguro[
    tipos_seguro['id_tipo_seguro'].notna() &
    tipos_seguro['tipo'].notna() &
    tipos_seguro['categoria'].notna() &
    tipos_seguro['riesgo_base'].notna()
].copy()

rechazados = tipos_seguro[
    tipos_seguro['id_tipo_seguro'].isna() |
    tipos_seguro['tipo'].isna() |
    tipos_seguro['categoria'].isna() |
    tipos_seguro['riesgo_base'].isna()
].copy()

MOTIVO DE RECHAZO

In [5]:
def motivo(row):

    motivos = []

    if pd.isna(row['id_tipo_seguro']):
        motivos.append("id_tipo_seguro_vacio")

    if pd.isna(row['tipo']):
        motivos.append("tipo_vacio")

    if pd.isna(row['categoria']):
        motivos.append("categoria_vacia")

    if pd.isna(row['riesgo_base']):
        motivos.append("riesgo_base_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

EXPORTAR ARCHIVOS

In [6]:
validos.to_csv("tipos_seguro_curated.csv", index=False)
rechazados.to_csv("tipos_seguro_rejects.csv", index=False)

CONECTAR CON POSTGRESQL

In [7]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_argueta:RuSM0PkNryjJpjcJs9z3LwZNjP3Iuoph@dpg-d6qu6ivgi27c73aaaar0-a.oregon-postgres.render.com/etl_seguros_c75s"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 42.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

CARGAR DATOS CON POSTGRESQL

In [8]:
validos.to_sql(
    'tipos_seguro_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'tipos_seguro_rejects',
    engine,
    if_exists='append',
    index=False
)

3

VALIDAR LA CARGA

In [9]:
pd.read_sql(
"SELECT * FROM tipos_seguro_curated LIMIT 10",
engine
)

   id_tipo_seguro        tipo    categoria  riesgo_base
0               2  Industrial  Empresarial         4.68
1               3  Industrial     Familiar         5.10
2               5        Auto  Empresarial         9.07
3               6  Industrial  Empresarial         2.52
4               7       Salud     Personal         0.92
5               8   Educación  Empresarial         7.42
6               9  Accidentes          Nan         5.68
7              10      Dental     Especial         2.70
8              11        Auto  Empresarial         4.33